import fs from 'fs';
import https from 'https';
import Papa from 'papaparse';

const sheet_id = '1jl0wFIfNEWYofEHN27Wb9UM1bdmoxzt5e2NUGyFijHY';
const urls = {
    'TIKTOK': `https://docs.google.com/spreadsheets/d/${sheet_id}/gviz/tq?tqx=out:csv&sheet=TIKTOK`,
    'META': `https://docs.google.com/spreadsheets/d/${sheet_id}/gviz/tq?tqx=out:csv&sheet=META`,
    'GOOGLE': `https://docs.google.com/spreadsheets/d/${sheet_id}/gviz/tq?tqx=out:csv&sheet=GOOGLE%20ADS`,
    'KOL': `https://docs.google.com/spreadsheets/d/${sheet_id}/gviz/tq?tqx=out:csv&sheet=KOL`
};

async function fetchCSV(url) {
    return new Promise((resolve, reject) => {
        https.get(url, (res) => {
            if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
                return resolve(fetchCSV(res.headers.location));
            }
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => resolve(data));
        }).on('error', err => reject(err));
    });
}

const cleanNumbers = (row) => {
    const cleaned = { ...row };
    for (let key in cleaned) {
        if (typeof cleaned[key] === 'string') {
            const withoutCommas = cleaned[key].replace(/,/g, '');
            if (cleaned[key].includes('Rp') || /^-?[\d,.]+$/.test(cleaned[key])) {
              // Remove currency symbols, spaces, and handle both . and , as separators
              let raw = cleaned[key].replace(/[Rp\s]/g, '');
              if (raw.includes('.') && raw.includes(',')) {
                  raw = raw.replace(/\./g, '').replace(',', '.');
              } else if (raw.includes('.') && raw.split('.').pop().length === 3) {
                  raw = raw.replace(/\./g, '');
              } else if (raw.includes(',') && raw.split(',').pop().length === 3) {
                  raw = raw.replace(/,/g, '');
              }
              const val = parseFloat(raw);
              if (!isNaN(val)) cleaned[key] = val;
            } else if (!isNaN(withoutCommas) && withoutCommas.trim() !== '' && !cleaned[key].includes('%')) {
                cleaned[key] = Number(withoutCommas);
            }
        }
    }
    const dateField = cleaned['Date(DD/MM/YYYY)'] || cleaned['Date Posting'] || cleaned['Aim Date Posting'];
    if (dateField) {
        const parts = dateField.split('/');
        if (parts.length === 3) {
            cleaned.normDate = `${parts[2]}-${parts[1].padStart(2, '0')}-${parts[0].padStart(2, '0')}`;
        } else if (dateField.includes('-')) {
            cleaned.normDate = dateField.substring(0, 10);
        }
    }
    return cleaned;
};

async function main() {
    const results = {};
    for (const [name, url] of Object.entries(urls)) {
        console.log(`Fetching ${name}...`);
        const csvData = await fetchCSV(url);
        const parsed = Papa.parse(csvData, { header: true, skipEmptyLines: true });
        results[name] = parsed.data.map(cleanNumbers);
    }

    const fileContent = `
// AUTOGENERATED FILE FROM GOOGLE SHEETS
export const tiktokAdsData = ${JSON.stringify(results.TIKTOK, null, 2)};
export const metaAdsData = ${JSON.stringify(results.META, null, 2)};
export const googleAdsData = ${JSON.stringify(results.GOOGLE, null, 2)};
export const kolData = ${JSON.stringify(results.KOL, null, 2)};
`;

    fs.writeFileSync('./src/data/realAdsData.js', fileContent);
    console.log('Saved to src/data/realAdsData.js');
}

main();
